SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;
SET COLLATION_CONNECTION = 'utf8mb4_unicode_ci';

INSERT INTO `categories` (`cate_name`, `is_featured`, `status`) VALUES
('sports', 1, 1),
('fashion', 1, 1),
('Business', 1, 1),
('Technology', 1, 1),
('Games', 1, 1),
('Life & Style', 1, 0),
('Photography', 1, 0);

INSERT INTO `users` (`username`, `password`, `email`, `role`, `status`) VALUES
('admin', MD5('admin123'), 'admin@example.com', 1, 1),
('khuy', MD5('khuy'), 'khuy@gmail.com', 0, 1),
('mkhoa', MD5('mkhoa'), 'mkhoa@gmail.com', 0, 1),
('ttin', MD5('ttin'), 'ttin@gmail.com', 0, 1),
('ntam', MD5('ntam'), 'ntam@gmail.com', 0, 1);


INSERT INTO `articles` (`title`, `content`, `thumbnail`, `original_image`, `published_date`, `views`, `user_id`, `cate_id`, `status`) VALUES
-- Bài 1: Sports
('Lợi ích của việc chơi thể thao hàng ngày', 'Thể thao mang lại nhiều lợi ích cho sức khỏe. Tập thể dục thường xuyên giúp cơ thể khỏe mạnh hơn. Chạy bộ là cách đơn giản để rèn luyện tim mạch. Bơi lội tốt cho cả cơ bắp và hô hấp. Yoga giúp giảm căng thẳng và tăng sự linh hoạt. Thể thao còn cải thiện tâm trạng của bạn. Những môn đồng đội như bóng đá xây dựng tinh thần hợp tác. Người lớn tuổi cũng nên vận động nhẹ nhàng. Đi bộ mỗi ngày là lựa chọn phổ biến. Thể thao giúp kiểm soát cân nặng hiệu quả. Nó cũng tăng cường hệ miễn dịch của cơ thể. Trẻ em cần chơi thể thao để phát triển thể chất. Các giải đấu thể thao tạo động lực cho mọi người. Tuy nhiên, cần tập đúng cách để tránh chấn thương. Khởi động trước khi chơi là rất quan trọng. Uống đủ nước trong quá trình vận động. Thể thao không chỉ là sức khỏe mà còn là niềm vui. Hãy chọn môn phù hợp với sở thích của bạn. Một cơ thể khỏe mạnh sẽ mang lại cuộc sống hạnh phúc. Thói quen này nên được duy trì suốt đời.', 'images/thumbnail/thumb_1.jpeg', 'images/image_1.avif', '2025-04-01 10:00:00', 100, 2, 1, 1),
-- Bài 2: Technology
('AI đang thay đổi thế giới như thế nào', 'Trí tuệ nhân tạo (AI) đang thay đổi cách chúng ta sống và làm việc. Những trợ lý ảo như Siri hay Alexa đã trở thành bạn đồng hành quen thuộc. AI giúp tự động hóa các công việc lặp đi lặp lại trong nhà máy. Trong y tế, nó hỗ trợ chẩn đoán bệnh chính xác hơn. Giáo dục cũng được cải thiện nhờ các nền tảng học tập thông minh. Các công ty lớn như Google và Microsoft đầu tư mạnh vào AI. Công nghệ này còn xuất hiện trong xe tự lái, hứa hẹn giảm tai nạn giao thông. Tuy nhiên, AI cũng đặt ra nhiều thách thức về đạo đức. Việc thu thập dữ liệu cá nhân khiến nhiều người lo ngại về quyền riêng tư. AI có thể thay thế con người trong một số ngành nghề. Nhưng nó cũng mở ra cơ hội việc làm mới trong lĩnh vực công nghệ. Các nhà khoa học đang nghiên cứu để AI trở nên an toàn hơn. Tại Việt Nam, AI bắt đầu được ứng dụng trong nông nghiệp. Những cánh đồng thông minh giúp tăng năng suất cây trồng. Người trẻ đang hào hứng học hỏi về lập trình AI. Chính phủ cũng khuyến khích phát triển công nghệ này. AI không chỉ là công cụ mà còn là động lực cho sự tiến bộ. Tương lai của AI phụ thuộc vào cách chúng ta sử dụng nó. Một thế giới thông minh hơn đang dần hình thành. Hãy sẵn sàng để đón nhận những thay đổi này.', 'images/thumbnail/thumb_2.jpeg', 'images/image_2.jpg', '2025-04-02 14:30:00', 214, 2, 4, 1),
-- Bài 3: Life & Style
('Ẩm thực đường phố: Hương vị cuộc sống', 'Hà Nội nổi tiếng với nền ẩm thực đường phố độc đáo. Phở bò là món ăn không thể bỏ qua khi đến đây. Bún chả thơm lừng với nước chấm chua ngọt làm say lòng thực khách. Bánh mì pate nóng giòn là lựa chọn tuyệt vời cho bữa sáng. Chả cá Lã Vọng mang hương vị đặc trưng của miền Bắc. Những gánh hàng rong bán xôi luôn tấp nập khách. Nem chua rán là món ăn vặt yêu thích của giới trẻ. Quán vỉa hè thường đông đúc vào buổi tối. Không khí nhộn nhịp làm tăng thêm phần thú vị khi thưởng thức món ăn. Người bán hàng thân thiện, luôn sẵn sàng trò chuyện với khách. Nguyên liệu tươi ngon được chọn lọc kỹ càng. Mỗi món ăn đều có câu chuyện riêng của nó. Ẩm thực Hà Nội là sự kết hợp giữa truyền thống và sáng tạo. Các món ăn thay đổi theo mùa để phù hợp khẩu vị. Du khách quốc tế thường bất ngờ với giá cả phải chăng. Ăn uống ở đây không chỉ no bụng mà còn là trải nghiệm văn hóa. Người dân Hà Nội rất tự hào về ẩm thực quê mình. Nhiều món đã được vinh danh trên thế giới. Hãy thử một lần để cảm nhận hương vị đặc biệt này. Ẩm thực đường phố Hà Nội thực sự là một kho báu.', 'images/thumbnail/thumb_3.jpeg', 'images/image_3.jpg', '2025-04-03 09:15:00', 63, 3, 6, 1),
-- Bài 4: Life & Style
('Sống chậm với thói quen đọc sách', 'Đọc sách mang lại nhiều lợi ích cho con người. Nó giúp mở rộng kiến thức về thế giới xung quanh. Sách là nguồn cảm hứng bất tận cho sự sáng tạo. Đọc sách còn cải thiện khả năng tập trung của bạn. Những cuốn tiểu thuyết hay làm phong phú tâm hồn. Sách khoa học giúp bạn hiểu rõ hơn về vũ trụ. Trẻ em đọc sách từ nhỏ sẽ phát triển tư duy tốt hơn. Người lớn tuổi đọc sách để giữ trí óc minh mẫn. Thói quen này còn giảm căng thẳng hiệu quả. Một cuốn sách hay có thể thay đổi cách nhìn của bạn về cuộc sống. Thư viện là nơi lý tưởng để tìm kiếm tri thức. Sách điện tử đang dần trở nên phổ biến hơn. Tuy nhiên, nhiều người vẫn yêu thích cảm giác lật từng trang giấy. Đọc sách giúp cải thiện vốn từ vựng và kỹ năng viết. Nó cũng là cách để thư giãn sau một ngày làm việc. Các câu chuyện trong sách thường truyền cảm hứng mạnh mẽ. Đọc sách cùng gia đình là hoạt động ý nghĩa. Nhiều người thành công đều có thói quen đọc sách. Hãy dành thời gian mỗi ngày để đọc một vài trang. Lợi ích của việc này sẽ khiến bạn bất ngờ.', 'images/thumbnail/thumb_4.jpeg', 'images/image_4.avif', '2025-04-04 16:20:00', 2, 4, 6, 1),
-- Bài 5: Life & Style
('Du lịch xanh: Lối sống bền vững', 'Du lịch bền vững đang trở thành xu hướng toàn cầu. Nó tập trung vào việc bảo vệ môi trường tự nhiên. Du khách được khuyến khích giảm thiểu rác thải nhựa. Các điểm đến ưu tiên sử dụng năng lượng tái tạo. Du lịch bền vững cũng tôn trọng văn hóa địa phương. Người dân bản địa được tham gia vào các hoạt động du lịch. Điều này giúp cải thiện đời sống kinh tế của họ. Các tour du lịch sinh thái ngày càng phổ biến. Du khách học cách sống hài hòa với thiên nhiên. Việc bảo tồn tài nguyên là mục tiêu chính của xu hướng này. Nhiều quốc gia đã ban hành chính sách hỗ trợ du lịch bền vững. Việt Nam cũng đang hướng tới mục tiêu này. Các khu nghỉ dưỡng xanh mọc lên ở nhiều nơi. Du khách có thể tham gia trồng cây để bù đắp khí thải. Hành động nhỏ như tái sử dụng chai nước cũng rất ý nghĩa. Du lịch bền vững không chỉ là trách nhiệm mà còn là niềm vui. Nó mang lại trải nghiệm sâu sắc hơn cho người tham gia. Mỗi chuyến đi đều góp phần bảo vệ hành tinh. Hãy lựa chọn cách du lịch có ý nghĩa hơn. Tương lai của Trái Đất phụ thuộc vào hành động của chúng ta hôm nay.', 'images/thumbnail/thumb_5.jpeg', 'images/image_5.avif', '2025-04-05 11:10:00', 145, 5, 6, 1),
-- Bài 6: Technology
('Hành trình phát triển của smartphone', 'Điện thoại đã trải qua một hành trình dài để phát triển. Chiếc điện thoại đầu tiên được Alexander Graham Bell phát minh năm 1876. Ban đầu, nó chỉ truyền được âm thanh qua dây. Những năm 1900, điện thoại bàn trở nên phổ biến hơn. Công nghệ không ngừng cải tiến qua từng thập kỷ. Đến những năm 1980, điện thoại di động ra đời. Motorola giới thiệu mẫu điện thoại cầm tay đầu tiên. Tuy nhiên, nó khá nặng và cồng kềnh. Sự xuất hiện của Nokia đánh dấu bước ngoặt lớn. Điện thoại dần trở nên nhỏ gọn và tiện lợi hơn. iPhone của Apple năm 2007 thay đổi hoàn toàn ngành công nghiệp. Màn hình cảm ứng trở thành tiêu chuẩn mới. Ngày nay, smartphone là vật bất ly thân của nhiều người. Chúng không chỉ để gọi mà còn để làm việc. Công nghệ 5G mang lại tốc độ vượt trội. Camera trên điện thoại ngày càng chất lượng hơn. Ứng dụng di động hỗ trợ mọi khía cạnh của cuộc sống. Điện thoại giờ đây còn tích hợp trí tuệ nhân tạo. Tương lai hứa hẹn nhiều đột phá hơn nữa. Lịch sử điện thoại là minh chứng cho sự sáng tạo của con người.', 'images/thumbnail/thumb_6.jpeg', 'images/image_6.avif', '2025-04-06 13:45:00', 187, 3, 4, 1),
-- Bài 7: Life & Style
('Bí quyết chăm sóc cây cảnh tại nhà', 'Chăm sóc cây cảnh trong nhà không hề khó. Đầu tiên, bạn cần chọn loại cây phù hợp với ánh sáng nhà mình. Cây kim tiền thích hợp với ánh sáng yếu. Cây lưỡi hổ lại rất dễ chăm sóc và bền bỉ. Tưới nước đúng cách là yếu tố quan trọng nhất. Đừng tưới quá nhiều để tránh úng rễ. Hãy kiểm tra độ ẩm của đất trước khi tưới. Ánh sáng tự nhiên giúp cây phát triển tốt hơn. Đặt cây gần cửa sổ là lựa chọn lý tưởng. Phân bón nên được sử dụng định kỳ mỗi tháng. Lau sạch lá để cây quang hợp hiệu quả hơn. Cắt tỉa cành khô để giữ dáng cây đẹp. Nhiệt độ phòng cũng ảnh hưởng đến cây. Tránh đặt cây gần máy lạnh hoặc lò sưởi. Một số cây còn giúp lọc không khí trong nhà. Chăm sóc cây mang lại cảm giác thư giãn. Nó cũng làm đẹp không gian sống của bạn. Hãy dành thời gian quan sát cây mỗi ngày. Điều này giúp bạn phát hiện sớm các vấn đề. Chăm sóc cây cảnh là thú vui đơn giản nhưng ý nghĩa.', 'images/thumbnail/thumb_2.jpeg', 'images/image_2.jpeg', '2025-04-07 08:30:00', 76, 4, 6, 1),
-- Bài 8: Life & Style
('Giáo dục trẻ em: Đầu tư cho tương lai', 'Giáo dục trẻ em là nền tảng cho tương lai. Trẻ cần được học từ khi còn nhỏ để phát triển toàn diện. Kiến thức giúp trẻ hiểu về thế giới xung quanh. Kỹ năng sống là điều không thể thiếu trong giáo dục. Trẻ em học cách tự lập từ những bài học cơ bản. Gia đình đóng vai trò quan trọng trong việc dạy dỗ. Trường học cung cấp môi trường học tập chuyên nghiệp. Giáo viên cần kiên nhẫn và sáng tạo khi giảng dạy. Trẻ em học tốt hơn khi được khuyến khích. Giáo dục không chỉ là học chữ mà còn là học đạo đức. Trẻ cần biết cách tôn trọng người khác. Các hoạt động ngoại khóa giúp trẻ phát triển thể chất. Công nghệ hỗ trợ việc học trở nên thú vị hơn. Tuy nhiên, cần kiểm soát thời gian sử dụng thiết bị điện tử. Giáo dục sớm giúp trẻ tự tin hơn trong cuộc sống. Nó cũng ảnh hưởng đến sự phát triển của xã hội. Một thế hệ được giáo dục tốt sẽ xây dựng đất nước mạnh mẽ. Cha mẹ nên đồng hành cùng con trong hành trình này. Đầu tư vào giáo dục là đầu tư cho tương lai. Tầm quan trọng của việc này không thể phủ nhận.', 'images/thumbnail/thumb_1.jpeg', 'images/image_1.avif', '2025-04-08 15:00:00', 92, 4, 6, 1),
-- Bài 9: Sports
('Chạy bộ: Môn thể thao cho mọi người', 'Thể thao mang lại nhiều lợi ích cho sức khỏe. Tập thể dục thường xuyên giúp cơ thể khỏe mạnh hơn. Chạy bộ là cách đơn giản để rèn luyện tim mạch. Bơi lội tốt cho cả cơ bắp và hô hấp. Yoga giúp giảm căng thẳng và tăng sự linh hoạt. Thể thao còn cải thiện tâm trạng của bạn. Những môn đồng đội như bóng đá xây dựng tinh thần hợp tác. Người lớn tuổi cũng nên vận động nhẹ nhàng. Đi bộ mỗi ngày là lựa chọn phổ biến. Thể thao giúp kiểm soát cân nặng hiệu quả. Nó cũng tăng cường hệ miễn dịch của cơ thể. Trẻ em cần chơi thể thao để phát triển thể chất. Các giải đấu thể thao tạo động lực cho mọi người. Tuy nhiên, cần tập đúng cách để tránh chấn thương. Khởi động trước khi chơi là rất quan trọng. Uống đủ nước trong quá trình vận động. Thể thao không chỉ là sức khỏe mà còn là niềm vui. Hãy chọn môn phù hợp với sở thích của bạn. Một cơ thể khỏe mạnh sẽ mang lại cuộc sống hạnh phúc. Thói quen này nên được duy trì suốt đời.', 'images/thumbnail/thumb_3.jpeg', 'images/image_3.jpeg', '2025-04-09 10:45:00', 128, 3, 1, 1),
-- Bài 10: Photography
('Chụp ảnh thiên văn qua kính thiên văn', 'Vũ trụ là một bí ẩn hấp dẫn con người. Kính thiên văn giúp chúng ta quan sát các vì sao. Galileo là người đầu tiên dùng kính để khám phá bầu trời. Ngày nay, công nghệ hiện đại mang lại hình ảnh rõ nét hơn. Các hành tinh như Sao Hỏa thu hút sự chú ý lớn. Dải Ngân Hà là nơi Trái Đất của chúng ta cư ngụ. Những ngôi sao xa xôi kể câu chuyện về vũ trụ. Kính Hubble đã chụp được nhiều hình ảnh tuyệt đẹp. Các nhà khoa học nghiên cứu để tìm kiếm sự sống ngoài hành tinh. Trẻ em cũng có thể học thiên văn qua kính nhỏ. Quan sát sao băng là trải nghiệm thú vị. Vũ trụ rộng lớn hơn những gì chúng ta tưởng tượng. Mỗi đêm, bầu trời mang đến một khung cảnh khác nhau. Công nghệ mới giúp phát hiện các thiên hà xa xôi. Thiên văn học là sự kết hợp giữa khoa học và trí tưởng tượng. Nó khơi dậy sự tò mò trong mỗi con người. Việt Nam cũng có những câu lạc bộ thiên văn. Hãy thử ngắm sao vào một đêm trời quang đãng. Vũ trụ luôn có điều gì đó để khám phá. Một chiếc kính thiên văn có thể mở ra cả một thế giới.', 'images/thumbnail/thumb_5.jpeg', 'images/image_5.avif', '2025-04-10 12:00:00', 56, 5, 7, 1),
-- Bài 11: Fashion
('Phong cách tối giản trong thời trang', 'Sống tối giản đang trở thành xu hướng hiện đại. Nó giúp bạn tập trung vào những điều thực sự quan trọng. Loại bỏ đồ đạc không cần thiết là bước đầu tiên. Một ngôi nhà gọn gàng mang lại cảm giác yên bình. Sống tối giản không có nghĩa là thiếu thốn. Nó khuyến khích sử dụng những thứ có giá trị lâu dài. Quần áo đơn giản nhưng chất lượng là lựa chọn thông minh. Tiêu dùng có ý thức giúp bảo vệ môi trường. Nhiều người cảm thấy nhẹ nhõm khi sống đơn giản hơn. Tối giản còn áp dụng trong công việc và suy nghĩ. Hãy ưu tiên những mục tiêu quan trọng nhất. Loại bỏ căng thẳng không cần thiết trong cuộc sống. Sống chậm lại để tận hưởng từng khoảnh khắc. Phong cách này phù hợp với mọi lứa tuổi. Nó giúp tiết kiệm thời gian và tiền bạc. Một cuộc sống tối giản mang lại sự tự do tinh thần. Bạn sẽ nhận ra mình không cần quá nhiều để hạnh phúc. Hãy thử áp dụng từng bước nhỏ. Kết quả sẽ khiến bạn bất ngờ. Sống tối giản là cách để tìm lại chính mình.', 'images/thumbnail/thumb_6.jpeg', 'images/image_6.avif', '2025-04-11 09:00:00', 173, 1, 2, 1),
-- Bài 12: Business
('Blockchain trong kinh doanh hiện đại', 'Blockchain đang thay đổi ngành tài chính toàn cầu. Nó là công nghệ đứng sau tiền điện tử như Bitcoin. Giao dịch được ghi lại một cách minh bạch và an toàn. Blockchain loại bỏ sự phụ thuộc vào trung gian. Ngân hàng tiết kiệm chi phí nhờ công nghệ này. Hợp đồng thông minh tự động hóa các thỏa thuận. Tính bảo mật cao giúp ngăn chặn gian lận. Nhiều công ty khởi nghiệp ứng dụng blockchain vào thanh toán. Tiền kỹ thuật số đang dần thay thế tiền mặt. Tuy nhiên, vẫn còn thách thức về quy định pháp lý. Các quốc gia có cách tiếp cận khác nhau với blockchain. Việt Nam cũng bắt đầu khám phá tiềm năng của nó. Doanh nghiệp nhỏ có thể hưởng lợi từ công nghệ này. Blockchain còn hỗ trợ quản lý chuỗi cung ứng. Dữ liệu không thể bị thay đổi sau khi ghi nhận. Điều này tạo niềm tin cho người dùng. Tương lai tài chính sẽ phụ thuộc nhiều vào blockchain. Các nhà đầu tư đang đổ tiền vào lĩnh vực này. Học hỏi về blockchain là xu hướng tất yếu. Công nghệ này hứa hẹn một hệ thống tài chính công bằng hơn.', 'images/thumbnail/thumb_1.jpeg', 'images/image_1.avif', '2025-04-12 14:00:00', 89, 2, 3, 1),
-- Bài 13: Life & Style
('Nấu ăn tại nhà: Nghệ thuật sống', 'Nấu ăn ngon tại nhà không cần phải phức tạp. Chọn nguyên liệu tươi là bước quan trọng nhất. Gia vị cần được sử dụng đúng liều lượng. Một chút sáng tạo làm món ăn thêm hấp dẫn. Nấu chậm giúp giữ được hương vị tự nhiên. Dao sắc giúp việc chuẩn bị nhanh hơn. Hãy thử các công thức từ nhiều nền ẩm thực. Nấu ăn cùng gia đình tạo không khí ấm cúng. Lò nướng mang lại kết quả tuyệt vời cho món bánh. Học cách cân bằng giữa các vị mặn, ngọt, chua. Thực hành thường xuyên giúp bạn tiến bộ. Xem video hướng dẫn là cách học hiệu quả. Đừng ngại thử nghiệm với món mới. Một bữa ăn ngon làm mọi người vui vẻ hơn. Dụng cụ bếp tốt giúp tiết kiệm thời gian. Trình bày món ăn cũng rất quan trọng. Nấu ăn là cách thể hiện tình yêu thương. Hãy kiên nhẫn khi món ăn chưa hoàn hảo. Mỗi lần nấu là một lần học hỏi. Bí quyết nằm ở sự đam mê và chăm chỉ.', 'images/thumbnail/thumb_2.jpeg', 'images/image_2.jpeg', '2025-04-13 10:30:00', 112, 3, 6, 1),
-- Bài 14: Technology
('Mạng xã hội và công nghệ hiện đại', 'Mạng xã hội đã thay đổi cách chúng ta giao tiếp. Facebook kết nối bạn bè trên toàn thế giới. Instagram là nơi chia sẻ những khoảnh khắc đẹp. Twitter mang đến tin tức nhanh chóng. Nó giúp doanh nghiệp tiếp cận khách hàng dễ dàng hơn. Tuy nhiên, mạng xã hội cũng có mặt trái. Thời gian sử dụng quá nhiều gây nghiện. Tin giả lan truyền nhanh chóng trên các nền tảng. Áp lực từ lượt thích ảnh hưởng đến tâm lý. Trẻ em cần được hướng dẫn khi dùng mạng xã hội. Nó cũng là công cụ để học tập và sáng tạo. Nhiều người kiếm tiền từ nội dung trực tuyến. Mạng xã hội phản ánh xu hướng xã hội hiện đại. Sự riêng tư là vấn đề đáng lo ngại. Người dùng nên kiểm soát thông tin cá nhân. Các chiến dịch xã hội được lan tỏa mạnh mẽ hơn. Mạng xã hội là con dao hai lưỡi. Cách sử dụng quyết định lợi hay hại. Hãy dùng nó một cách thông minh. Tương lai của mạng xã hội vẫn còn nhiều điều để khám phá.', 'images/thumbnail/thumb_3.jpeg', 'images/image_3.jpeg', '2025-04-14 16:00:00', 201, 4, 4, 1),
-- Bài 15: Life & Style
('Hành động nhỏ bảo vệ môi trường', 'Bảo vệ môi trường bắt đầu từ hành động nhỏ. Tái chế rác thải giúp giảm ô nhiễm. Sử dụng túi vải thay cho túi nilon là lựa chọn thông minh. Tiết kiệm điện góp phần giảm khí thải. Trồng cây xanh làm không khí trong lành hơn. Hạn chế dùng nhựa một lần là xu hướng hiện nay. Mọi người nên phân loại rác tại nhà. Đi bộ hoặc xe đạp thay vì xe máy khi có thể. Tuyên truyền ý thức bảo vệ môi trường rất quan trọng. Trẻ em cần học về điều này từ nhỏ. Các công ty cũng nên áp dụng sản xuất xanh. Nước sạch là tài nguyên cần được bảo vệ. Ô nhiễm không khí đang là vấn đề toàn cầu. Hành động của mỗi người đều tạo ra sự khác biệt. Hãy tắt đèn khi không sử dụng. Sử dụng năng lượng tái tạo nếu có điều kiện. Một môi trường sạch mang lại sức khỏe tốt hơn. Thói quen tốt cần được duy trì lâu dài. Bảo vệ môi trường là trách nhiệm chung. Hãy bắt đầu từ hôm nay để cứu lấy hành tinh.', 'images/thumbnail/thumb_5.jpeg', 'images/image_5.avif', '2025-04-15 11:00:00', 167, 5, 6, 1),
-- Bài 16: Games
('Sự phát triển của ngành game', 'Trò chơi điện tử đã thay đổi qua nhiều thập kỷ. Những năm 1970, Pong là tựa game đơn giản đầu tiên. Atari mở ra kỷ nguyên giải trí tại nhà. Nintendo mang đến Mario và Zelda huyền thoại. PlayStation định nghĩa lại đồ họa game. Máy tính cá nhân cũng trở thành nền tảng chơi game. Trò chơi trực tuyến xuất hiện vào những năm 2000. Esports giờ đây là ngành công nghiệp lớn. Công nghệ thực tế ảo mang lại trải nghiệm mới. Game mobile phổ biến nhờ smartphone. Các nhà phát triển không ngừng sáng tạo nội dung. Trò chơi giúp giải trí và giảm căng thẳng. Tuy nhiên, chơi quá mức có thể gây nghiện. Cha mẹ cần kiểm soát thời gian chơi của trẻ. Game còn được dùng trong giáo dục. Đồ họa ngày càng chân thực hơn bao giờ hết. Cộng đồng game thủ toàn cầu rất sôi động. Việt Nam cũng có nhiều tựa game nội địa. Tương lai hứa hẹn nhiều đột phá hơn. Trò chơi điện tử là một phần của văn hóa hiện đại.', 'images/thumbnail/thumb_6.jpeg', 'images/image_6.avif', '2025-04-16 13:00:00', 245, 3, 5, 1),
-- Bài 17: Business
('Tiết kiệm tiền cho doanh nghiệp nhỏ', 'Tiết kiệm tiền là kỹ năng cần thiết trong cuộc sống. Đầu tiên, hãy lập ngân sách hàng tháng. Ghi lại mọi khoản chi tiêu để kiểm soát tốt hơn. Tránh mua sắm impulsively không cần thiết. Mở tài khoản tiết kiệm riêng là ý tưởng hay. Đặt mục tiêu cụ thể để có động lực. Hạn chế ăn ngoài để tiết kiệm chi phí. Sử dụng phiếu giảm giá khi mua sắm. Tận dụng các chương trình khuyến mãi. Tiền tiết kiệm nên được đầu tư khôn ngoan. Học cách sửa chữa thay vì mua mới. Chia nhỏ thu nhập thành các phần hợp lý. Tránh nợ tín dụng không cần thiết. Kiểm tra hóa đơn để phát hiện sai sót. Tiết kiệm năng lượng cũng là cách giảm chi phí. Hãy kiên nhẫn vì tiết kiệm cần thời gian. Một khoản dự phòng giúp bạn an tâm hơn. Thói quen tốt sẽ mang lại kết quả lớn. Tài chính ổn định là nền tảng cho tương lai. Bắt đầu tiết kiệm từ những điều nhỏ nhất.', 'images/thumbnail/thumb_1.jpeg', 'images/image_1.avif', '2025-04-17 09:30:00', 78, 2, 3, 1),
-- Bài 18: Fashion
('Áo dài: Biểu tượng thời trang Việt', 'Văn hóa Việt Nam giàu bản sắc và lịch sử. Áo dài là biểu tượng của vẻ đẹp truyền thống. Tết Nguyên Đán là lễ hội lớn nhất trong năm. Người dân quây quần bên mâm cỗ ngày Tết. Bánh chưng tượng trưng cho đất trời. Làng nghề thủ công lưu giữ kỹ thuật xưa. Dân ca quan họ ngọt ngào và sâu lắng. Hội làng mang không khí vui tươi đặc trưng. Trẻ em thích thú với trò chơi dân gian. Tín ngưỡng thờ cúng tổ tiên rất phổ biến. Văn hóa Việt Nam là sự giao thoa độc đáo. Các giá trị truyền thống được gìn giữ qua thế hệ. Du khách quốc tế yêu thích nét văn hóa này. Lễ hội hoa đăng thắp sáng dòng sông. Nghệ thuật múa rối nước là di sản đặc biệt. Gia đình luôn là trung tâm của văn hóa. Sự hiếu khách là nét đẹp của người Việt. Văn hóa thay đổi nhưng vẫn giữ cốt lõi. Hãy trân trọng và bảo tồn di sản này. Việt Nam tự hào với bề dày văn hóa của mình.', 'images/thumbnail/thumb_3.jpeg', 'images/image_3.jpeg', '2025-04-18 15:15:00', 132, 4, 2, 1),
-- Bài 19: Life & Style
('Thiền định: Bí quyết sống khỏe', 'Thiền định mang lại nhiều lợi ích cho tâm trí. Nó giúp bạn giảm căng thẳng hiệu quả. Chỉ cần 10 phút mỗi ngày để thư giãn. Thiền cải thiện khả năng tập trung của bạn. Nhiều người cảm thấy bình an sau khi thiền. Nó còn giúp kiểm soát cảm xúc tốt hơn. Thiền không yêu cầu dụng cụ phức tạp. Một góc yên tĩnh là đủ để bắt đầu. Nghiên cứu cho thấy thiền tốt cho sức khỏe tim mạch. Người lớn tuổi thiền để giữ tinh thần minh mẫn. Trẻ em cũng có thể học thiền để thư giãn. Thiền định phù hợp với mọi lứa tuổi. Nó giúp cải thiện chất lượng giấc ngủ. Một số công ty khuyến khích nhân viên thiền. Thiền là cách kết nối với chính mình. Hãy thử các bài thiền có hướng dẫn. Kiên trì sẽ mang lại kết quả rõ rệt. Thiền không chỉ là trào lưu mà là lối sống. Sức khỏe tinh thần quan trọng như thể chất. Hãy dành thời gian để thiền mỗi ngày.', 'images/thumbnail/thumb_4.jpeg', 'images/image_4.avif', '2025-04-19 10:00:00', 95, 5, 6, 1),
-- Bài 20: Photography
('Chụp ảnh kỳ quan thế giới', 'Các kỳ quan thế giới là niềm tự hào của nhân loại. Kim tự tháp Giza là công trình cổ đại kỳ vĩ. Vạn Lý Trường Thành thể hiện sự kiên trì của con người. Taj Mahal là biểu tượng của tình yêu vĩnh cửu. Machu Picchu ẩn mình giữa núi rừng Peru. Petra ở Jordan mang vẻ đẹp huyền bí. Tháp Eiffel là biểu tượng của nước Pháp. Mỗi kỳ quan kể một câu chuyện lịch sử. Du khách từ khắp nơi đến chiêm ngưỡng chúng. Việc bảo tồn các kỳ quan rất quan trọng. Công nghệ giúp tái hiện vẻ đẹp xưa cũ. Một số kỳ quan đã bị hư hại theo thời gian. UNESCO công nhận và bảo vệ những di sản này. Việt Nam cũng có Vịnh Hạ Long trong danh sách. Khám phá kỳ quan là ước mơ của nhiều người. Chúng là minh chứng cho sự sáng tạo của con người. Mỗi địa điểm mang một nét độc đáo riêng. Hãy lên kế hoạch để thăm ít nhất một kỳ quan. Trải nghiệm này sẽ để lại ấn tượng mãi mãi. Thế giới còn nhiều điều kỳ diệu để khám phá.', 'images/thumbnail/thumb_2.jpeg', 'images/image_2.jpeg', '2025-04-20 12:30:00', 183, 2, 7, 1);

INSERT INTO `contact` (`name`, `email`, `phone`, `title`, `content`, `created_at`, `status`) VALUES
('Nguyễn Văn An', 'an.nguyen@example.com', '0912345678', 'Hỏi về bài viết', 'Tôi muốn biết thêm thông tin về bài viết gần đây trên trang của bạn.', '2025-05-01 08:30:00', 'pending'),
('Trần Thị Bình', 'binh.tran@example.com', '0923456789', 'Phản hồi chậm', 'Tôi đã gửi liên hệ trước đó nhưng chưa nhận được phản hồi.', '2025-05-02 09:15:00', 'pending'),
('Lê Minh Châu', 'chau.le@example.com', '0934567890', 'Đề xuất cải thiện', 'Trang web nên có thêm tính năng tìm kiếm nâng cao.', '2025-05-02 14:20:00', 'in_progress'),
('Phạm Quốc Đạt', 'dat.pham@example.com', '0945678901', 'Lỗi hiển thị', 'Trang tin tức hiển thị lỗi trên thiết bị di động.', '2025-05-03 10:00:00', 'resolved'),
('Hoàng Thị Em', 'em.hoang@example.com', '0956789012', 'Hợp tác quảng cáo', 'Công ty chúng tôi muốn hợp tác quảng cáo trên trang của bạn.', '2025-05-03 16:45:00', 'resolved'),
('Vũ Văn Phong', 'phong.vu@example.com', '0967890123', 'Yêu cầu xóa bài viết', 'Vui lòng xóa bài viết có thông tin không chính xác.', '2025-05-04 11:30:00', 'rejected'),
('Đỗ Thị Giang', 'giang.do@example.com', '0978901234', 'Câu hỏi về sự kiện', 'Sự kiện sắp tới được tổ chức ở đâu?', '2025-05-04 13:00:00', 'pending'),
('Bùi Quang Huy', 'huy.bui@example.com', '0989012345', 'Góp ý nội dung', 'Bài viết về công nghệ cần cập nhật thêm thông tin mới.', '2025-05-05 07:50:00', 'in_progress'),
('Mai Thị Kim', 'kim.mai@example.com', '0990123456', 'Hỗ trợ kỹ thuật', 'Tôi không thể đăng nhập vào tài khoản trên trang.', '2025-05-05 15:25:00', 'resolved'),
('Ngô Văn Long', 'long.ngo@example.com', '0901234567', 'Liên hệ quảng cáo', 'Tôi muốn thảo luận về gói quảng cáo trên trang tin tức.', '2025-05-06 09:10:00', 'in_progress');

INSERT INTO `newsletterSubscribers` (`email`) VALUES
INSERT INTO `newsletterSubscribers` (`email`) VALUES
('subscriber1@example.com'),
('subscriber2@example.com'),
('subscriber3@example.com');

INSERT INTO `websiteInfo` (`address`, `email`, `facebook_url`, `youtube_url`, `copyright`) VALUES
('123 Đường ABC, Quận XYZ, Thành phố ABC', 'newsfeed@example.com', 'https://www.facebook.com/Newsfeed', 'https://www.youtube.com/Newsfeed', '© 2025 Newsfeed Inc. All rights reserved.');

INSERT INTO `comments` (`email`, `content`, `article_id`, `created_at`) VALUES
('nguyenthanhlong@gmail.com', 'Bài viết rất hay và bổ ích. Tôi đã áp dụng một số lời khuyên về chạy bộ và thấy sức khỏe cải thiện rõ rệt.', 1, '2025-04-26 09:15:00'),
('tranminhhieu@example.com', 'Tôi thường xuyên chơi thể thao và hoàn toàn đồng ý với những lợi ích mà bài viết đề cập. Mong tác giả chia sẻ thêm về chế độ dinh dưỡng phù hợp cho người tập thể thao.', 1, '2025-04-26 14:30:00'),
('phamthuylinh@hotmail.com', 'Bài viết này đã thay đổi cách nhìn của tôi về tập thể dục. Trước đây tôi nghĩ chỉ cần tập mạnh là tốt, nhưng giờ tôi hiểu tầm quan trọng của việc khởi động và tập đúng cách. Cảm ơn tác giả!', 1, '2025-04-27 10:45:00'),
('hoangvanthanh@gmail.com', 'AI đang thay đổi cuộc sống của chúng ta theo nhiều cách không ngờ. Tôi làm việc trong lĩnh vực IT và thấy rằng bài viết này đã nêu rất chính xác những xu hướng hiện tại.', 2, '2025-04-28 08:30:00'),
('lethihoa@example.com', 'Tôi lo ngại về vấn đề đạo đức khi AI phát triển quá nhanh. Liệu chúng ta có đang chuẩn bị đủ tốt cho những thách thức này?', 2, '2025-04-28 14:45:00'),
('nguyenducminh@hotmail.com', 'Tôi đã thử nhiều món ăn đường phố ở Hà Nội và phải công nhận rằng phở bò và bún chả thực sự tuyệt vời. Bài viết mô tả rất chính xác hương vị đặc trưng của ẩm thực Hà Nội.', 3, '2025-04-29 09:20:00'),
('vuhoangnam@gmail.com', 'Đọc sách thực sự đã thay đổi cuộc đời tôi. Tôi bắt đầu đọc 30 phút mỗi ngày và thấy tư duy của mình mở rộng đáng kể. Cảm ơn tác giả đã chia sẻ những lợi ích tuyệt vời này.', 4, '2025-04-29 16:10:00'),
('tranquynhanh@example.com', 'Du lịch xanh là xu hướng cần được khuyến khích. Tôi đã tham gia một tour du lịch sinh thái ở Việt Nam và rất ấn tượng với cách họ bảo vệ môi trường tự nhiên.', 5, '2025-04-30 11:25:00'),
('phamvantruong@gmail.com', 'Smartphone đã phát triển nhanh chóng trong 10 năm qua. Tôi còn nhớ chiếc Nokia đầu tiên của mình và so với iPhone bây giờ thật sự là một sự khác biệt lớn. Bài viết rất hay và đầy đủ thông tin.', 6, '2025-04-30 15:40:00'),
('nguyenthianh@example.com', 'Tôi đã thử áp dụng một số mẹo chăm sóc cây cảnh từ bài viết này và thực sự hiệu quả. Cây của tôi đã phát triển tốt hơn nhiều. Cảm ơn tác giả!', 7, '2025-05-01 10:15:00'),
('levanquang@hotmail.com', 'Giáo dục trẻ em là nền tảng cho tương lai. Tôi là một giáo viên và hoàn toàn đồng ý với quan điểm của bài viết. Chúng ta cần đầu tư nhiều hơn vào giáo dục sớm.', 8, '2025-05-01 14:30:00'),
('tranthihien@gmail.com', 'Tôi đã bắt đầu chạy bộ được 3 tháng và cảm thấy sức khỏe cải thiện rõ rệt. Bài viết này đã cung cấp cho tôi nhiều thông tin hữu ích để tập luyện hiệu quả hơn.', 9, '2025-05-02 08:45:00'),
('phamthanhbinh@example.com', 'Tôi là một nhiếp ảnh gia nghiệp dư và rất thích chụp ảnh thiên văn. Bài viết này đã cho tôi nhiều gợi ý hay để cải thiện kỹ năng của mình.', 10, '2025-05-02 16:20:00'),
('nguyenvanminh@gmail.com', 'Phong cách tối giản đã giúp tôi sống có ý thức hơn. Tôi đã loại bỏ nhiều đồ không cần thiết và cảm thấy cuộc sống nhẹ nhàng hơn rất nhiều.', 11, '2025-05-03 09:30:00'),
('tranthithu@example.com', 'Tôi làm việc trong ngành tài chính và thấy rằng blockchain đang thực sự thay đổi cách chúng ta giao dịch. Bài viết này đã giải thích rất rõ ràng về công nghệ phức tạp này.', 12, '2025-05-03 13:45:00'),
('levantuan@hotmail.com', 'Nấu ăn tại nhà không chỉ tiết kiệm mà còn là niềm vui. Tôi đã thử công thức trong bài viết và gia đình tôi rất thích. Mong tác giả chia sẻ thêm nhiều công thức nữa.', 13, '2025-05-04 10:10:00'),
('phamthihang@gmail.com', 'Mạng xã hội có cả mặt tích cực và tiêu cực. Tôi nghĩ chúng ta cần dạy trẻ em cách sử dụng chúng một cách có trách nhiệm. Bài viết đã nêu rất đúng những điểm này.', 14, '2025-05-04 15:30:00');
